#!/usr/bin/perl -w
# vi:ts=4:sw=4:ai:
use strict;
use Data::Dumper;

# point to the UM lib dir
use lib qw {
	../lib
};

# use the required UM module(s)
use UglyMUG::Log;

# variables
my ($log);

# create a new instance
# /home/herlpacker/chisel/Development/SourceForge/UglyLogs
$log = UglyMUG::Log->new (
	'logfile'			=> '/home/herlpacker/chisel/Development/SourceForge/UglyLogs/data/muddles.logtest',
	'outdir'			=> '/home/herlpacker/chisel/Development/SourceForge/UglyLogs/data/logs',

	'email_list'		=> '/home/herlpacker/chisel/Development/SourceForge/UglyLogs/data/email.list',
	'admin_info'		=> '/home/herlpacker/chisel/Development/SourceForge/UglyLogs/data/admin.info',

	'log_headers'		=> '/home/herlpacker/chisel/Development/SourceForge/UglyLogs/data/logs/headers',

	'log_from_address'	=> 'UglyMUG Logs <uglylogs@uglymug.org.uk>',

	# for testing
	'test_mail_to'		=> 'Chisel Wright <chisel@herlpacker.co.uk>',
	'test_print_mail'	=> 0,
	

	'DEBUG'				=> 0,
)
	or die "can't create new instance of UglyMUG::Log";

# parse and process the logfile
$log->parse_logfile;

# send player logs
$log->send_player_logs;

# send admin logs
$log->send_admin_logs;
